# Translation updated at Sat Jul 03 2021 10:39:29 GMT+0000 (Coordinated Universal Time)
translate chinese strings:

    # game/y-options.rpy_L15_0
    old "Friendship with Benefits"
    new "Friendship with Benefits"

    # game/y-options.rpy_L32_0
    old "Art, Coding and Writing:\nTwistedScarlett60\nSpelling and Grammar Checking: Jinjo Bytes\n\nAll music is royalty free and used with permission.\nHowever, considering the subject of my game, please don't hesistate to message me if I'm using your content and you're not comfortable associating with it.\n\nMusic:\nBread - {a=https://soundcloud.com/lukrembo}Lukrembo{/a}\nDissociation - {a=https://soundcloud.com/naoya-sakamata}Naoya Sakamata{/a}\nAnother Perspective - {a=https://soundcloud.com/idealismus}Idealism{/a}\nBefore you Fall Asleep - {a=https://soundcloud.com/jhovebeats}Jhove{/a}\nArt of Silence - {a=https://soundcloud.com/uniqofficial/art-of-silence}Uniq{/a}\nFire and Thunder - {a=https://soundcloud.com/cjbeards}Cjbeards{/a}\ninlove - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nMr Kill Yourself - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nLips - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nOni - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nEuphoric Filth - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\ninpeace - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\ninlove - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nYandere Complex - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nlorncloud - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nHopelessness - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nSlow Death - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nCyberia lyr3 - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nThe Maw - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nToe Wizard - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nBlue Boi - {a=https://soundcloud.com/lakeyinspired}Lakey Inspired{/a}\nUntitled - {a=https://soundcloud.com/lakeyinspired}Lakey Inspired{/a}\nConquered Emotions - {a=https://soundcloud.com/user-811451507}Yakuzee Beatz{/a}\nSoul Aches - {a=https://soundcloud.com/user-811451507}Yakuzee Beatz{/a}\nThat's One Sly Cat - {a=https://soundcloud.com/artificial-music}Artificial Music{/a}\nAbstract Foilage - {a=https://soundcloud.com/artificial-music}Artificial Music{/a}\nSecrets - {a=https://soundcloud.com/user-602857531}Michael Hildreth{/a}\nGood Day - {a=https://www.youtube.com/LowFrequencyMusic}Low Frequency Music{/a}\nSad Piano - Mark Clark\nPina Colada - {a=https://soundcloud.com/silentpartnermusic}Silent Partner{/a}\nTranquil - {a=https://soundcloud.com/martynaslau}Whitesand{/a}\nBeen Here Before - {a=https://soundcloud.com/no_mic}NO MIC{/a}\nStuck in the Machine - {a=https://soundcloud.com/no_mic}NO MIC{/a}\nDanse Morialta - {a=https://incompetech.com/}Kevin MacLeod{/a}\nHip Jazz - {a=www.bensound.com}Benjamin Tissot{/a}\nBasic Metal 6 - {a=http://teknoaxe.com/Home.php}TeknoAXE{/a}\nJazz Organ Trio Cool Blue - Doug Maxwell\nLa Fille aux Cheveux de lin - Claude Debussy\n\n\nSound Effects from https://www.zapsplat.com"
    new "美术、代码及剧本：\nTwistedScarlett60\n拼写及语法校对：Jinjo Bytes\n\n游戏中的所有音乐均为免费音乐，且均是在获得允许后才进行使用的。\n但考虑到本游戏中的角色，如涉及到抄袭以及使您感到不适，请立即联系我们。\n\n音乐：\nBread - {a=https://soundcloud.com/lukrembo}Lukrembo{/a}\nDissociation - {a=https://soundcloud.com/naoya-sakamata}Naoya Sakamata{/a}\nAnother Perspective - {a=https://soundcloud.com/idealismus}Idealism{/a}\nBefore you Fall Asleep - {a=https://soundcloud.com/jhovebeats}Jhove{/a}\nArt of Silence - {a=https://soundcloud.com/uniqofficial/art-of-silence}Uniq{/a}\nFire and Thunder - {a=https://soundcloud.com/cjbeards}Cjbeards{/a}\ninlove - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nMr Kill Yourself - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nLips - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nOni - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nEuphoric Filth - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\ninpeace - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\ninlove - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nYandere Complex - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nlorncloud - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nHopelessness - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nSlow Death - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nCyberia lyr3 - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nThe Maw - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nToe Wizard - {a=https://www.patreon.com/sewerslvt}Sewerslvt{/a}\nBlue Boi - {a=https://soundcloud.com/lakeyinspired}Lakey Inspired{/a}\nUntitled - {a=https://soundcloud.com/lakeyinspired}Lakey Inspired{/a}\nConquered Emotions - {a=https://soundcloud.com/user-811451507}Yakuzee Beatz{/a}\nSoul Aches - {a=https://soundcloud.com/user-811451507}Yakuzee Beatz{/a}\nThat's One Sly Cat - {a=https://soundcloud.com/artificial-music}Artificial Music{/a}\nAbstract Foilage - {a=https://soundcloud.com/artificial-music}Artificial Music{/a}\nSecrets - {a=https://soundcloud.com/user-602857531}Michael Hildreth{/a}\nGood Day - {a=https://www.youtube.com/LowFrequencyMusic}Low Frequency Music{/a}\nSad Piano - Mark Clark\nPina Colada - {a=https://soundcloud.com/silentpartnermusic}Silent Partner{/a}\nTranquil - {a=https://soundcloud.com/martynaslau}Whitesand{/a}\nBeen Here Before - {a=https://soundcloud.com/no_mic}NO MIC{/a}\nStuck in the Machine - {a=https://soundcloud.com/no_mic}NO MIC{/a}\nDanse Morialta - {a=https://incompetech.com/}Kevin MacLeod{/a}\nHip Jazz - {a=www.bensound.com}Benjamin Tissot{/a}\nBasic Metal 6 - {a=http://teknoaxe.com/Home.php}TeknoAXE{/a}\nJazz Organ Trio Cool Blue - Doug Maxwell\nLa Fille aux Cheveux de lin - Claude Debussy\n\n\n音效来源：https://www.zapsplat.com"

