name: Sync with Paratranz

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  sync:
    name: sync
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull from Paratranz
        env:
          token: ${{ secrets.PARATRANZ_TOKEN }}
        run: 'wget -O latest.zip --header="Authorization: $token" https://paratranz.cn/api/projects/2414/artifacts/download'
      - name: Update
        run: |
          rm -rf paratranz
          unzip latest.zip "utf8/*"
          mv utf8 paratranz
      - name: Sort & Reconvert
        run: node reconvert.js
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '"paratranz" "game/tl/chinese"'
          default_author: github_actions
          message: 'CI: Sync with Paratranz'
          push: true
