name: Sync with Paratranz

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull from Paratranz
        env:
          token: ${{ secrets.PARATRANZ_TOKEN }}
        run: 'wget -O latest.zip --header="Authorization: $token" https://paratranz.cn/api/projects/2414/artifacts/download'
      - name: Update
        run: |
          rm -rf paratranz
          unzip latest.zip "utf8/*"
          mv utf8 paratranz
      - name: Sort
        run: node sort_paratranz.js
      - name: Reconvert
        run: node reconvert_paratranz.js
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: paratranz
          default_author: github_actions
          message: Sync with Paratranz
          push: true
